apply plugin: 'net.corda.plugins.cordapp'

cordapp {
    targetPlatformVersion corda_platform_version
    minimumPlatformVersion corda_platform_version
    contract {
        name "Health Records Contracts"
        vendor "Health Records Corp"
        licence "Apache License, Version 2.0"
        versionId 1
    }
}

dependencies {
    cordaProvided "$corda_core_release_group:corda-core:$corda_core_release_version"
    implementation 'javax.persistence:javax.persistence-api:2.2'
}
